from flask import Flask

header_text = '''
    <html>\n<head> <title>Flask Test Application</title> </head>\n<body>'''
page_content = '''
    <p>This is a sample webpage generated by Flask.</p>\n'''
footer_text = '''</body>\n</html>'''

# request handler function for the home/index page
def index():
	return header_text + page_content + footer_text

# setting up the application context
application = Flask(__name__)

# add a rule for the index page.
application.add_url_rule('/', 'index', index, methods=['GET', 'POST'])

# run the app.
if __name__ == "__main__":
    # Setting debug to True enables debug output. This line should be
    # removed before deploying a production app.
    application.debug = True
    application.run()